# This file was generated by swiftpm2nix.
{
  workspaceStateFile = ./workspace-state.json;
  hashes = {
    "swift-asn1" = "sha256-9WrDipPXevLnevsu3VEF2/W1l38vZIrXDCorpKZ6edo=";
    "swift-atomics" = "sha256-Ho3/BDUwAVGG26u8Jz2j1mwqFRcLc+DTlqTyGelM+Gc=";
    "swift-collections" = "sha256-igD3I9BHDGQAU6pAwfb2nAJ+p3BWH8iaPg7A7gq/Ej0=";
    "swift-crypto" = "sha256-PfaOjxs4uLnpCYeDRBF9/KnoIhU98P8WZpnOnfizkmI=";
    "swift-nio" = "sha256-/WiblOShmgtJILqVwx6evuIt0Qf7I+KHJ7enPHuN+vA=";
    "swift-system" = "sha256-JYdYLOGkM2vbyab2XG6V818UmBLHAQB7VghfPbLduME=";
  };
}
